#!/usr/bin/env python
"""Parse the candidate DESI-2 filters

"""
import os, pdb
import numpy as np
import fitsio
from astropy.table import Table
from speclite import filters
import astropy.units as u
import matplotlib.pyplot as plt

#F = fitsio.read('desi2-filters.fits')
F = Table.read('desi2-filters.fits')

for ifilt in np.arange(5):
    wave = F['WAVELENGTH']
    resp = F['FILTER'][:, ifilt]
    wave = np.hstack([np.min(wave)-0.1, wave, np.max(wave)+0.1])
    resp = np.hstack([0.0, resp, 0.0])

    ff = filters.FilterResponse(
        wavelength=wave * u.Angstrom,
        response=resp / np.max(resp),
        meta=dict(group_name='desi2', band_name='g{}'.format(ifilt+1)))

    ff.save('./')

desi2 = filters.load_filters('desi2-g1', 'desi2-g2', 'desi2-g3', 'desi2-g4', 'desi2-g5', 'decam2014-g')
filters.plot_filters(desi2, wavelength_limits=(3500,6200), cmap='jet')

plt.savefig('desi2-filters.png')
